CREATE TABLE IF NOT EXISTS btg.unmasked_clients
(
    id int NOT NULL GENERATED ALWAYS AS IDENTITY,
    "account_number" varchar(50),
    "holder_tax_identification" varchar(50),
    holder_name varchar(100),
    user_name varchar(50),
    "user_user_email" varchar(100),
    "user_phone_number" varchar(15),
    "user_is_owner" BOOLEAN,
    "coholder_tax_identification"  VARCHAR(14),
    coholder_name VARCHAR(100),
    data_extract date  DEFAULT CURRENT_DATE,
    CONSTRAINT btg_api_clients_pkey PRIMARY KEY (id))

----------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS btg.unmasked_positions
(
    id integer NOT NULL DEFAULT nextval('btg.btg_api_positions_id_seq'::regclass),
    "market_name" character varying(255) COLLATE pg_catalog."default",
    "market_abbreviation" character varying(255) COLLATE pg_catalog."default",
    "position_date" date,
    "end_position_value" double precision,
    "start_position_value" double precision,
    "account_number" double precision,
    product_type character varying(255) COLLATE pg_catalog."default",
    data_extracao date,
    "share_value" double precision,
    "cota_cetipada_fundo_externo" character varying(255) COLLATE pg_catalog."default",
    "processing_date_time" date,
    "fund_security_code" double precision,
    "fund_fund_name" character varying(255) COLLATE pg_catalog."default",
    "fund_security_code" double precision,
    "fund_fund_cge_code" double precision,
    "fund_fund_cnpj_code" double precision,
    "fund_date_portfolio" date,
    "fund_manager_name" text COLLATE pg_catalog."default",
    "fund_manager_cge_code" double precision,
    "fund_fund_liquidity" double precision,
    "fund_bench_mark" character varying(255) COLLATE pg_catalog."default",
    "fund_es_tipo_portfolio" double precision,
    "fund_tipo_cvm" double precision,
    "fund_entity_type" character varying(255) COLLATE pg_catalog."default",
    "fund_related_security_code_class" double precision,
    "fund_related_security_code_fund" double precision,
    "fund_related_class_cge_code" double precision,
    "fund_related_fund_cge_code" double precision,
    "cost_price" double precision,
    "income_tax" double precision,
    "virtual_iof" double precision,
    "net_asset_value" double precision,
    "gross_asset_value" double precision,
    "acquisition_date" date,
    "number_of_shares" double precision,
    "acquisition_number" double precision,
    "origem_amortizacao" character varying(255) COLLATE pg_catalog."default",
    "cost_value" double precision,
    "cota_cetipada" character varying(255) COLLATE pg_catalog."default",
    "accounting_group_code" character varying(255) COLLATE pg_catalog."default",
    "issuer" text COLLATE pg_catalog."default",
    "issue_date" date,
    "security_code" double precision,
    "issuer_cge_code" double precision,
    "price_type" double precision,
    "value_type" character varying(255) COLLATE pg_catalog."default",
    "yield" double precision,
    "ticker" character varying(255) COLLATE pg_catalog."default",
    "reference_index_name" character varying(255) COLLATE pg_catalog."default",
    "reference_index_value" text COLLATE pg_catalog."default",
    "index_yield_Rate" double precision,
    "maturity_date" date,
    "quantity" double precision,
    "price" double precision,
    "gross_value" double precision,
    "iof_tax" double precision,
    "net_value" double precision,
    "is_liquidity" character varying(255) COLLATE pg_catalog."default",
    "fts_id" double precision,
    "is_repo" character varying(255) COLLATE pg_catalog."default",
    "cetip_code" character varying(255) COLLATE pg_catalog."default",
    "selic_code" double precision,
    "isin" character varying(255) COLLATE pg_catalog."default",
    "tax_free" character varying(255) COLLATE pg_catalog."default",
    "issuer_type" character varying(255) COLLATE pg_catalog."default",
    "projection" character varying(255) COLLATE pg_catalog."default",
    "lag" character varying(255) COLLATE pg_catalog."default",
    "default" character varying(255) COLLATE pg_catalog."default",
    "yieldAvg" double precision,
    "debt_early_termination_schedules" double precision,
    "debt_early_termination_schedules_Index_rate_multiplier" double precision,
    "debt_early_termination_schedules_Rate" double precision,
    "debt_early_termination_schedules_type" character varying(255) COLLATE pg_catalog."default",
    "debt_early_termination_schedules_early_termination_period_from_date_ti" date,
    "debt_early_termination_schedules_early_termination_period_to_datetime" date,
    "acquisition_quantity" double precision,
    "yield_to_maturity" double precision,
    "initial_investment_value" double precision,
    "initial_investment_quantity" double precision,
    "complement_yield" double precision,
    "transfer_id" double precision,
    "interface_date" date,
    "price_income_tax" double precision,
    "price_virtual_iof" double precision,
    "datetime_update" date,
    "is_virtual" character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT btg_api_positions_pkey PRIMARY KEY (id)
)

------------------------------------------------------------------------------------------------------------------------------------------------------------------------


CREATE TABLE IF NOT EXISTS interno.unmasked_comissao_bankers
(
    id int NOT NULL GENERATED ALWAYS AS IDENTITY,
    "codigo_cliente" int,
    "nome_cliente"   varchar(100),
    "taxa_adm"       double precision,
    "custodiante"    varchar(50),
    "data_contrato"  date,
    "data_inicio_taxa_adm" date,
    "data_fim_taxa_adm"    date,
    "tipo_taxa_Adm"        varchar(50),
    "produtos_ponderacao"  varchar(100),
    "escritorio"           varchar(50),
    "assessor_comercial"   varchar(50),
    "gerente_comercial"    varchar(50),
    "diretor_comercial"    varchar(50),
    "repasse_netz_assessor" double precision,
    "repasse_assessor_comercial" double precision,
    "repasse_gerente_comercial" double precision,
    "repasse_diretor_comercial" double precision,
    "email_assessor"  varchar(200),
    data_extracao date,
    data_referencia date,
    patrimonio_liquido double precision,
    valor_cobrado double precision,
    repasse_netz double precision,
    repasse_assessor double precision,
    repasse_diretor double precision,
    repasse_gerente double precision,
    taxa_netz double precision,
    taxa_assessor double precision,
    taxa_diretor double precision,
    taxa_gerente double precision,
    "canal" varchar(50),
    "taxa_performance" double precision,
    "cpf_cnpj" varchar(14),
    "executivo_comercial" varchar(50),
    "repasse_executivo_comercial" double precision,
    CONSTRAINT int_comissao_bankers_pkey PRIMARY KEY (id))





