CREATE OR REPLACE PROCEDURE  vortx.sp_carga_carteira_json_ativos_sor_para_sot()
LANGUAGE plpgsql
AS $$
BEGIN

WITH   vortx_api_carteira_json_sor
AS (SELECT
    REPLACE(REPLACE(REPLACE(COALESCE("data_atual"::date::text, ''), ' ', ''), '-', ''), '/', '') ||
    REPLACE(REPLACE(REPLACE(COALESCE("cnpj_fundo"::text, ''), ' ', ''), '-', ''), '/', '') ||
    REPLACE(REPLACE(REPLACE(COALESCE("titulo", ''), ' ', ''), '-', ''), '/', '') ||
    REPLACE(REPLACE(REPLACE(COALESCE("detalhes", ''), ' ', ''), '-', ''), '/', '') AS chave_forte,
                                                empresa,
                                                carteira,
												nome,
												titulo,
												tipo_fundo,
												fundo,
												cnpj,
												quantidade,
												valor_cota,
												valor_bruto, 
												tributos,
												valor_liquido,
												isin,
												tipo_moeda, 
												tipo_ativo,
												cnpj_fundo,
												nome_resumido,
												status, 
												pl,
												quantidade_cotas,
												variacao_cota,
												tipo_condominio,
												data_atual, 
												despesa, 
												detalhes,
												valor, 
												instituicao,
												saldo, 
												nome_mercado, 
												tipo, 
												codigo_custodia,
												emissor, 
												data_compra, 
												data_emissao, 
												data_vencimento,
												indexador,
												porcentagem_indexador, 
												taxa,
												quantidade_livre,
												quantidade_bloqueio,
												valor_compra,
												pu_custo,
												curva_atual,
												pu_mercado,
												mercado_atual, 
												ate_vencimento,
												is_ativo_vortx,
												codigo_ativo_vortx, 
												data_extracao

FROM vortx.unmasked_carteira_json_ativos_sor AS SOR),

vortx_api_carteira_json_sot
AS 
    (SELECT  
    REPLACE(REPLACE(REPLACE(COALESCE("data_atual"::date::text, ''), ' ', ''), '-', ''), '/', '') ||
    REPLACE(REPLACE(REPLACE(COALESCE("cnpj_fundo"::text, ''), ' ', ''), '-', ''), '/', '') ||
    REPLACE(REPLACE(REPLACE(COALESCE("titulo", ''), ' ', ''), '-', ''), '/', '') ||
    REPLACE(REPLACE(REPLACE(COALESCE("detalhes", ''), ' ', ''), '-', ''), '/', '') AS chave_forte,
                                                empresa,
                                                carteira,
												nome,
												titulo,
												tipo_fundo,
												fundo,
												cnpj,
												quantidade,
												valor_cota,
												valor_bruto, 
												tributos,
												valor_liquido,
												isin,
												tipo_moeda, 
												tipo_ativo,
												cnpj_fundo,
												nome_resumido,
												status, 
												pl,
												quantidade_cotas,
												variacao_cota,
												tipo_condominio,
												data_atual, 
												despesa, 
												detalhes,
												valor, 
												instituicao,
												saldo, 
												nome_mercado, 
												tipo, 
												codigo_custodia,
												emissor, 
												data_compra, 
												data_emissao, 
												data_vencimento,
												indexador,
												porcentagem_indexador, 
												taxa,
												quantidade_livre,
												quantidade_bloqueio,
												valor_compra,
												pu_custo,
												curva_atual,
												pu_mercado,
												mercado_atual, 
												ate_vencimento,
												is_ativo_vortx,
												codigo_ativo_vortx, 
												data_extracao
FROM                                            vortx.unmasked_carteira_json_ativos  AS  SOT)


INSERT INTO vortx.unmasked_carteira_json_ativos(empresa,
                                                carteira,
												nome,
												titulo,
												tipo_fundo,
												fundo,
												cnpj,
												quantidade,
												valor_cota,
												valor_bruto, 
												tributos,
												valor_liquido,
												isin,
												tipo_moeda, 
												tipo_ativo,
												cnpj_fundo,
												nome_resumido,
												status, 
												pl,
												quantidade_cotas,
												variacao_cota,
												tipo_condominio,
												data_atual, 
												despesa, 
												detalhes,
												valor, 
												instituicao,
												saldo, 
												nome_mercado, 
												tipo, 
												codigo_custodia,
												emissor, 
												data_compra, 
												data_emissao, 
												data_vencimento,
												indexador,
												porcentagem_indexador, 
												taxa,
												quantidade_livre,
												quantidade_bloqueio,
												valor_compra,
												pu_custo,
												curva_atual,
												pu_mercado,
												mercado_atual, 
												ate_vencimento,
												is_ativo_vortx,
												codigo_ativo_vortx, 
												data_extracao)

SELECT 		   								    SOR.empresa,
                                                SOR.carteira,
											    SOR.nome,
												SOR.titulo,
												SOR.tipo_fundo,
												SOR.fundo,
												SOR.cnpj,
												SOR.quantidade,
												SOR.valor_cota,
												SOR.valor_bruto, 
												SOR.tributos,
												SOR.valor_liquido,
												SOR.isin,
												SOR.tipo_moeda, 
												SOR.tipo_ativo,
												SOR.cnpj_fundo,
												SOR.nome_resumido,
												SOR.status, 
												SOR.pl,
												SOR.quantidade_cotas,
												SOR.variacao_cota,
												SOR.tipo_condominio,
												SOR.data_atual, 
												SOR.despesa, 
												SOR.detalhes,
												SOR.valor, 
												SOR.instituicao,
												SOR.saldo, 
												SOR.nome_mercado, 
												SOR.tipo, 
												SOR.codigo_custodia,
												SOR.emissor, 
												SOR.data_compra, 
												SOR.data_emissao, 
												SOR.data_vencimento,
												SOR.indexador,
												SOR.porcentagem_indexador, 
												SOR.taxa,
												SOR.quantidade_livre,
												SOR.quantidade_bloqueio,
												SOR.valor_compra,
												SOR.pu_custo,
												SOR.curva_atual,
												SOR.pu_mercado,
												SOR.mercado_atual, 
												SOR.ate_vencimento,
												SOR.is_ativo_vortx,
												SOR.codigo_ativo_vortx, 
												SOR.data_extracao
FROM                   vortx_api_carteira_json_sor        AS  SOR
LEFT JOIN              vortx_api_carteira_json_sot        AS  SOT             ON    SOR.chave_forte = SOT.chave_forte
WHERE                  SOT.chave_forte IS  NULL;

END;
$$;










 

